name: spw-env
channels:
  - pytorch
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - aws-c-auth=0.9.0=h3318fae_10
  - aws-c-cal=0.9.1=h5e3027f_0
  - aws-c-common=0.12.3=hb9d3cd8_0
  - aws-c-compression=0.3.1=hafb2847_5
  - aws-c-event-stream=0.5.4=haaa725d_10
  - aws-c-http=0.10.1=hd7992d4_3
  - aws-c-io=0.19.1=h7b43961_3
  - aws-c-mqtt=0.13.0=h7b3935a_4
  - aws-c-s3=0.8.0=h365f71b_1
  - aws-c-sdkutils=0.2.4=hafb2847_0
  - aws-checksums=0.2.7=hafb2847_1
  - aws-crt-cpp=0.32.6=h96107e3_3
  - aws-sdk-cpp=1.11.510=hf282fd2_9
  - azure-core-cpp=1.14.0=h5cfcd09_0
  - azure-identity-cpp=1.10.0=h113e628_0
  - azure-storage-blobs-cpp=12.13.0=h3cf044e_1
  - azure-storage-common-cpp=12.8.0=h736e048_1
  - azure-storage-files-datalake-cpp=12.12.0=ha633028_1
  - blas=1.0=mkl
  - blosc=1.21.6=he440d0b_1
  - bottleneck=1.5.0=py311h9f3472d_0
  - branca=0.8.1=pyhd8ed1ab_0
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py311hfdbb021_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.6.15=hbd8a1cb_0
  - cached-property=1.5.2=py_0
  - cartopy=0.24.0=py311h7db5c69_0
  - certifi=2025.6.15=pyhd8ed1ab_0
  - cffi=1.17.1=py311hf29c0ef_0
  - cftime=1.6.4=py311h9f3472d_1
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=py311h06a4308_0
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.2=py311hd18a35c_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dask-core=2025.5.1=pyhd8ed1ab_0
  - dask-geopandas=0.5.0=pyhd8ed1ab_0
  - debugpy=1.8.14=py311hfdbb021_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - filelock=3.17.0=py311h06a4308_0
  - folium=0.19.5=pyhd8ed1ab_0
  - fonttools=4.58.0=py311h2dc5d0c_0
  - freetype=2.13.3=ha770c72_1
  - freexl=2.0.0=h9dce30a_2
  - geopandas=1.0.1=pyhd8ed1ab_3
  - geopandas-base=1.0.1=pyha770c72_3
  - geos=3.13.1=h97f6797_0
  - geotiff=1.7.4=h239500f_2
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=hd590300_0
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py311h5eee18b_0
  - greenlet=3.2.2=py311hfdbb021_0
  - h2=4.2.0=pyhd8ed1ab_0
  - h5py=3.13.0=nompi_py311hb639ac4_100
  - hdf4=4.2.15=h2a13503_7
  - hdf5=1.14.3=nompi_hdf9ad27_105
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.6.1=pyha770c72_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=9.2.0=pyhfb0248b_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.0=pyhd8ed1ab_0
  - json-c=0.18=h6688a6e_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py311hd18a35c_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250127.1=cxx17_hbbce691_0
  - libaec=1.1.3=h59595ed_0
  - libarchive=3.7.7=h75ea233_4
  - libarrow=20.0.0=h9b1bdb9_4_cpu
  - libarrow-acero=20.0.0=hcb10f89_4_cpu
  - libarrow-dataset=20.0.0=hcb10f89_4_cpu
  - libarrow-substrait=20.0.0=h1bed206_4_cpu
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.13.0=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgdal-core=3.10.3=hcefe1ba_8
  - libgfortran-ng=8.2.0=hdf63c60_1
  - libgfortran5=15.1.0=hcea5267_2
  - libgomp=15.1.0=h767d61c_2
  - libgoogle-cloud=2.36.0=hc4361e1_1
  - libgoogle-cloud-storage=2.36.0=h0121fbd_1
  - libgrpc=1.71.0=h8e591d7_1
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - libkml=1.3.0=hf539b9f_1021
  - liblzma=5.8.1=hb9d3cd8_1
  - libnetcdf=4.9.2=nompi_h00e09a9_116
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.29=ha39b09d_0
  - libopentelemetry-cpp=1.20.0=hd1b1c89_0
  - libopentelemetry-cpp-headers=1.20.0=ha770c72_0
  - libparquet=20.0.0=h081d1f1_4_cpu
  - libpng=1.6.47=h943b412_0
  - libprotobuf=5.29.3=h501fc15_1
  - libre2-11=2024.07.02=hba17884_3
  - librttopo=1.1.0=hd718a1a_18
  - libsodium=1.0.20=h4ab18f5_0
  - libspatialite=5.1.0=he17ca71_14
  - libsqlite=3.49.2=hee588c1_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=15.1.0=h4852527_2
  - libthrift=0.21.0=h0e7cc3e_0
  - libtiff=4.7.0=hf01ce69_5
  - libutf8proc=2.10.0=h202a827_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.8=h4bc477f_0
  - libxslt=1.1.39=h76b75d6_0
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb9d3cd8_2
  - locket=1.0.0=pyhd8ed1ab_0
  - lxml=5.4.0=py311hbd2c71b_0
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=hd590300_1001
  - mapclassify=2.8.1=pyhd8ed1ab_1
  - markupsafe=3.0.2=py311h2dc5d0c_1
  - matplotlib-base=3.10.3=py311h2b939e6_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - memory_profiler=0.61.0=pyhd8ed1ab_1
  - minizip=4.0.10=h05a5f5f_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py311h5eee18b_0
  - mkl_fft=1.3.1=py311h30b3d60_0
  - mkl_random=1.2.2=py311hba01205_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py311h06a4308_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - netcdf4=1.7.2=nompi_py311hae66bec_101
  - networkx=3.4.2=pyh267e887_2
  - nlohmann_json=3.12.0=h3f2d84a_0
  - numpy=1.24.3=py311hc206e33_0
  - numpy-base=1.24.3=py311hfd5febd_0
  - obspy=1.4.0=py311h4c7f6c3_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openssl=3.5.0=h7b32b05_1
  - orc=2.1.2=h17f744e_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.2.3=py311h7db5c69_3
  - parso=0.8.4=pyhd8ed1ab_1
  - partd=1.4.2=pyhd8ed1ab_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.45=hc749103_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.2.1=py311h1322bbf_0
  - pip=25.1.1=pyh8b19718_0
  - platformdirs=4.3.7=py311h06a4308_0
  - pooch=1.8.2=py311h06a4308_0
  - proj=9.6.0=h0054346_1
  - prometheus-cpp=1.3.0=ha5d0236_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyarrow=20.0.0=py311h38be061_0
  - pyarrow-core=20.0.0=py311h4854187_0_cpu
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyogrio=0.11.0=py311hf6089d3_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyproj=3.7.1=py311h0960b38_1
  - pyshp=2.3.1=py311h06a4308_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.12=h9e4cc4f_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=7_cp311
  - pytorch-mutex=1.0=cpu
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py311h2dc5d0c_2
  - pyzmq=26.4.0=py311h7deb3e3_0
  - qhull=2020.2=h434a139_5
  - re2=2024.07.02=h9925aae_3
  - readline=8.2=h8c095d6_2
  - requests=2.32.3=pyhd8ed1ab_1
  - s2n=1.5.21=h7ab7c64_0
  - scikit-learn=1.6.1=py311h57cc02b_0
  - scipy=1.10.1=py311hc206e33_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.1.0=pyhff2d567_0
  - sgp4=2.24=py311hd18a35c_1
  - shapely=2.1.0=py311h3dc67b8_0
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=h8bd8927_1
  - sqlalchemy=2.0.40=py311h9ecbd09_0
  - sqlite=3.49.2=h9eae976_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.4=py311h9f3472d_0
  - sympy=1.13.3=py311h06a4308_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_h4845f30_101
  - toolz=1.0.0=pyhd8ed1ab_1
  - tornado=6.4.2=py311h9ecbd09_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.13.2=h0e9735f_0
  - typing_extensions=4.13.2=pyh29332c3_0
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py311h9ecbd09_0
  - uriparser=0.9.8=hac33072_0
  - urllib3=2.4.0=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xarray=2024.11.0=py311h06a4308_0
  - xerces-c=3.2.5=h988505b_2
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xyzservices=2025.4.0=pyhd8ed1ab_0
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py311h9ecbd09_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - asympdirscalculator==1.0.13
      - bezpy==0.1.1
      - fsspec==2024.6.1
      - nvidia-cublas-cu12==12.8.3.14
      - nvidia-cuda-cupti-cu12==12.8.57
      - nvidia-cuda-nvrtc-cu12==12.8.61
      - nvidia-cuda-runtime-cu12==12.8.57
      - nvidia-cudnn-cu12==9.7.1.26
      - nvidia-cufft-cu12==11.3.3.41
      - nvidia-cufile-cu12==1.13.0.11
      - nvidia-curand-cu12==10.3.9.55
      - nvidia-cusolver-cu12==11.7.2.55
      - nvidia-cusparse-cu12==12.5.7.53
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.8.61
      - nvidia-nvtx-cu12==12.8.55
      - powerlaw==1.5
      - psutil==7.0.0
      - pysecs==0.3.0
      - torch==2.7.0+cu128
      - torchaudio==2.7.0+cu128
      - torchvision==0.22.0+cu128
      - triton==3.3.0
prefix: /home/pve_ubuntu/miniconda3/envs/spw-env
